[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version", "description", "readme"]
name = "rarfile"
requires-python = ">=3.9"
authors = [
    {name = "Marko Kreen", email = "markokr@gmail.com"},
]
license = "ISC"
license-files = ["LICENSE"]
keywords = ['rar', 'unrar', 'archive']
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Archiving :: Compression",
]

[project.urls]
Homepage = "https://github.com/markokr/rarfile"
Source = "https://github.com/markokr/rarfile"
Issues = "https://github.com/markokr/rarfile/issues"
Documentation = "https://rarfile.readthedocs.io"

[project.optional-dependencies]
cryptography = [
    "cryptography",
    "cryptography<=42.0.8; python_version == '3.9' and platform_python_implementation == 'PyPy'",
    "cryptography<=45.0.7; python_version == '3.10' and platform_python_implementation == 'PyPy'",
]
pycryptodome = [
    "pycryptodome",
]
test = [
    "coverage==7.4.4",
    "pytest==8.1.1",
    "pytest-cov==5.0.0",
    "pytest-xdist==3.5.0",
]
docs = [
    "sphinx==7.2.6",
    "docutils==0.20.1",
]
lint = [
    "pylint==3.1.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "rarfile.__version__"}

[tool.cibuildwheel]
skip = ["*_i686", "*_ppc64le", "*_s390x"]

[tool.cibuildwheel.macos]
archs = ["universal2"]

[tool.cibuildwheel.windows]
archs = ["native"]