#
# https://docs.github.com/en/actions
# https://github.com/actions
#
# https://formulae.brew.sh/
# https://packages.msys2.org/
#

name: CI

on:
  pull_request: {}
  push: {}

jobs:

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39

      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - uses: extractions/setup-just@v4

      - name: "Run Lint"
        run: |
          just lint

  test:
    name: |
      Test - ${{ matrix.os }} / ${{ matrix.python-version }}${{
        matrix.crypto != '' && format(' / {0}', matrix.crypto) || ''
      }}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', '3.14' ]
        crypto: [ 'cryptography' ]
        include:
          - os: 'ubuntu-latest'
            python-version: '3.9'
            crypto: ''
          - os: 'ubuntu-latest'
            python-version: '3.9'
            crypto: 'pycryptodome'
          - os: 'ubuntu-latest'
            python-version: 'pypy3.9'
            crypto: 'cryptography'
          - os: 'ubuntu-latest'
            python-version: 'pypy3.10'
            crypto: 'cryptography'
          - os: 'ubuntu-latest'
            python-version: 'pypy3.11'
            crypto: 'cryptography'

    steps:
      - name: "Checkout"
        uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39

      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python-version}}

      - name: "Install archivers (linux)"
        if: ${{runner.os == 'Linux'}}
        run: |
          sudo -nH apt-get -qqy install unrar unar libarchive-tools p7zip-rar
          unrar
          unar -h
          bsdtar -h
          7z i

      - name: "Install archivers (macos)"
        if: ${{runner.os == 'macOS'}}
        run: |
          brew install rar unar libarchive sevenzip
          unrar
          unar -h
          bsdtar -h
          7z i
          7zz i

      - name: "Install archivers (windows)"
        if: ${{runner.os == 'Windows'}}
        shell: cmd
        run: |
          set "PATH=c:\msys64\usr\bin;%PATH%"
          pacman -S --noconfirm --needed bsdtar p7zip
          curl -sS -o unrarw64.exe https://www.rarlab.com/rar/unrarw64.exe
          7z x unrarw64.exe
          unrar
          bsdtar -h
          7z i

      - uses: extractions/setup-just@v4

      - name: Run tests
        run: |
          just test "${{ matrix.python-version }}" "${{ matrix.crypto }}"
